// Auto-generated by Arduino CLI Wrapper: Embed Assets
// Sketch: BasicTest
// Index:
// - assets/directory/1.txt -> assets_directory_1_txt / assets_directory_1_txt_len
// - assets/directory/2.txt -> assets_directory_2_txt / assets_directory_2_txt_len
// - assets/directory/test/3.txt -> assets_directory_test_3_txt / assets_directory_test_3_txt_len
// - assets/hello.txt -> assets_hello_txt / assets_hello_txt_len

#pragma once
#include <cstddef>
#include <cstdint>

#if defined(PROGMEM)
#include <pgmspace.h>
#endif

// assets/directory/1.txt
alignas(4) const uint8_t assets_directory_1_txt[] PROGMEM = {
  0x31, 0x0D, 0x0A, 0x32, 0x0D, 0x0A, 0x33, 0x0D, 0x0A, 0x34, 0x0D, 0x0A,
  0x35, 0x0D, 0x0A
};
const size_t assets_directory_1_txt_len = 15;

// assets/directory/2.txt
alignas(4) const uint8_t assets_directory_2_txt[] PROGMEM = {
  0x32
};
const size_t assets_directory_2_txt_len = 1;

// assets/directory/test/3.txt
alignas(4) const uint8_t assets_directory_test_3_txt[] PROGMEM = {
  0x33, 0x74, 0x65, 0x78, 0x74, 0x0D, 0x0A
};
const size_t assets_directory_test_3_txt_len = 7;

// assets/hello.txt
alignas(4) const uint8_t assets_hello_txt[] PROGMEM = {
  0x68, 0x65, 0x6C, 0x6C, 0x6F, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x65,
  0x6E, 0x64, 0x0A
};
const size_t assets_hello_txt_len = 15;

constexpr size_t assets_file_count = 4;
const char* const assets_file_names[assets_file_count] = {
  "/directory/1.txt",
  "/directory/2.txt",
  "/directory/test/3.txt",
  "/hello.txt"
};
const uint8_t* const assets_file_data[assets_file_count] = {
  assets_directory_1_txt,
  assets_directory_2_txt,
  assets_directory_test_3_txt,
  assets_hello_txt
};
const size_t assets_file_sizes[assets_file_count] = {
  assets_directory_1_txt_len,
  assets_directory_2_txt_len,
  assets_directory_test_3_txt_len,
  assets_hello_txt_len
};
