/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef EMBEDFS_VERSION_H
#define EMBEDFS_VERSION_H

#define EMBEDFS_VERSION_MAJOR 0
#define EMBEDFS_VERSION_MINOR 1
#define EMBEDFS_VERSION_PATCH 1
#define EMBEDFS_VERSION_STR "0.1.1"

#endif // EMBEDFS_VERSION_H
