/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef EMBEDFS_VERSION_H
#define EMBEDFS_VERSION_H

#define EMBEDFS_VERSION_MAJOR 1
#define EMBEDFS_VERSION_MINOR 0
#define EMBEDFS_VERSION_PATCH 0
#define EMBEDFS_VERSION_STR "1.0.0"

#endif // EMBEDFS_VERSION_H
